# nginx
apiVersion: v1
kind: Service
metadata:
  name: nginx
  annotations:
    cloud.google.com/backend-config: '{"default":"nginx-backend-config"}'  # needs the BackendConfig annotation
spec:
  type: ClusterIP
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
